NIFTY100 = [
    "ADANIENT","ADANIPORTS","APOLLOHOSP","ASIANPAINT","AXISBANK",
    "BAJAJ-AUTO","BAJFINANCE","BAJAJFINSV","BEL","BHARTIARTL",
    "BPCL","BRITANNIA","CIPLA","COALINDIA","DRREDDY",
    "EICHERMOT","GRASIM","HCLTECH","HDFCBANK","HDFCLIFE",
    "HEROMOTOCO","HINDALCO","HINDUNILVR","ICICIBANK","INDUSINDBK",
    "INFY","ITC","JSWSTEEL","KOTAKBANK","LT",
    "M&M","MARUTI","NESTLEIND","NTPC","ONGC",
    "POWERGRID","RELIANCE","SBILIFE","SBIN","SHRIRAMFIN",
    "SUNPHARMA","TATACONSUM","TATAMOTORS","TATASTEEL","TCS",
    "TECHM","TITAN","ULTRACEMCO","WIPRO",

    "ABB","ACC","ADANIENSOL","AMBUJACEM","AUROPHARMA",
    "BAJAJHLDNG","BANKBARODA","BOSCHLTD","CANBK","CHOLAFIN",
    "COLPAL","DABUR","DLF","DIVISLAB","GAIL",
    "GODREJCP","HAL","HAVELLS","HDFCAMC","ICICIGI",
    "ICICIPRULI","INDIGO","INDUSTOWER","IRCTC","JINDALSTEL",
    "L&TFH","LICI","LODHA","LUPIN","MARICO",
    "MUTHOOTFIN","NAUKRI","NMDC","OBEROIRLTY","OFSS",
    "PAGEIND","PEL","PETRONET","PIIND","PNB",
    "POLYCAB","PFC","RECLTD","SAIL","SBICARD",
    "SIEMENS","SRF","TORNTPHARM","TRENT","TVSMOTOR",
    "UBL","VEDL","VOLTAS","ZEEL"
]